[options]
    default_indent = 4
    home_files_number = 10
    relativenumber = true

    bootstrap_after = "myvimrc#after"

[[layers]]
name = 'core#tabline'
enable = false # disabled because tabline is messing up maximized nvim-qt 

[[layers]]
name = 'incsearch'

#  key         mode        description
#  /           n/v         incsearch forward
#  ?           n/v         incsearch backward
#  g/          n/v         incsearch stay
#  n           n           nohlsearch n
#  N           n           nohlsearch N
#  *           n           nohlsearch *
#  g*          n           nohlsearch g*
#  #           n           nohlsearch #
#  g#          n           nohlsearch g#
#  z/          n           incsearch fuzzy /
#  z?          n           incsearch fuzzy ?
#  zg?         n           incsearch fuzzy g?
#  <Space>/    n           incsearch easymotion

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#html'
